-- Migration number: 0001 	 2023-10-29T04:54:28.690Z
ALTER TABLE
    memes
ADD
    COLUMN is_active INTEGER NOT NULL DEFAULT 1;

ALTER TABLE
    memes
ADD
    COLUMN description TEXT;

ALTER TABLE
    memes
ADD
    COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE
    memes
ADD
    COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;