# If you are only using Pages + D1, you only need the below in your wrangler.toml to interact with D1 locally.
[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "mmfldr-db"
database_id = "5344a9ae-f5c3-4021-a99d-fe9e6c92adbd" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development
migrations_dir = "d1/migrations"

[[r2_buckets]]
binding = 'R2' # <~ valid JavaScript variable name
bucket_name = 'r2_mmflder_bucket'